### ISSUE TITLE
Adding some flag that tracks if this is creator's first signup or re-opt in

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#102]
## Context
- https://github.com/Joystream/atlas/issues/3449

## Scope

Adding some flag that tracks if this is creator's first signup or re-opt in

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203772033600682) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@zeeshanakram3 to confirm if the original date of sign up is not overwritten by repeat sign up.

**Comment by zeeshanakram3** [comment]
> @zeeshanakram3 to confirm if the original date of sign up is not overwritten by repeat sign up.

Confirmed that original signup date is not overwritten when user re opt-in. So closing this issue
