### ISSUE TITLE
Only sync videos that are 1month old and newer

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#106]
@dmtrjsg commented on [Wed Dec 21 2022](https://github.com/Joystream/marketing/issues/326)

## Context

In order to keep the content relevant and avoid syncing up backlog of old videos with news and reviews that are dated, I suggest to cap the "age" of the synced videos to 1 month. 

This way it will be also easier to manage the budget for the payouts. 

## Scope
- [ ] Only sync videos that are 1 month old and newer

**Comment by dmtrjsg** [comment]
Do we sync from old to new ones?
Which channels does this get applied to based on category? (news vs podcasts)

**Comment by bedeho** [comment]
> I suggest to cap the "age" of the synced videos to 1 month.

This is based on the premise that people are mainly publishing information that is tied to contemporary concerns, news, etc. I don't think that is true in general, not even remotely so. Lots of educational materials are timeless, and people may also like going back and viewing back catalgoues, so I think we should not have such a limit of any kind.
