### ISSUE TITLE
Couple of question about yt-sync

### ISSUE THREAD

**Issue by singulart** [Joystream/youtube-synch#110]
Hey team. 

Got couple of simple questions about youtube-sync, hope you don't mind
1. Does youtube-sync require any $JOY for storage or transaction fees?
2. Are there any validations on storage node API side to protect against uploading of non-video content? 
Thanks!

**Comment by bedeho** [comment]
> Does youtube-sync require any $JOY for storage or transaction fees?

Yes, infra must do all the on-chain stuff, so yes. Our chain is quite cheap, so shouldnt be that bad at almost all realistic scales in the near term, but yes. I am sure there will be ample council or gateway funding for proper gateways onboarding serious content and creators, but just speculating.

> Are there any validations on storage node API side to protect against uploading of non-video content?
Thanks!

No, that will need to be filtered out on the gateway side, currently this is not super easy, but its possible. Keep in mind, Joystream is meant ot be an open platform, so people may wish to publish any sort of media, like audio, documents, etc., not just video files.
