### ISSUE TITLE
Conduct YT-Synch Fault Tolerance QA and Bugfixing

### ISSUE THREAD

**Issue by bedeho** [Joystream/youtube-synch#130]
# Background

Basically do whatever was planned here https://github.com/Joystream/youtube-synch/issues/129

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203869309703862) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
- [ ] Prepare collaborator accounts with misc balances: 0, very low (1joy), a little more than very low (2Joy). Memberships need to be created for this.
> [info is here](https://docs.google.com/spreadsheets/d/1U3VEUFjTykIB69LiNQYPKz3M54lC_y-U3F5Zjn_JDOo/edit#gid=942113611)
- [ ] If the youtube channel gets deleted, syncing service should handle it gracefully by marking the state of the given channel as OptedOut
- [ ] If the user revokes its channel's access to the Gleev app, then his access_token & refresh_token instantly become invalid. Hence ensure that BE can properly handle such scenarios without affecting other components and the state of other channels. Also, ensure that the state of such channel is set to OptedOut with its ingestion disabled.

**Comment by zeeshanakram3** [comment]
## Fault Tolerance QA Summary

This comment describes the results of YT-synch fault tolerance QA which was planned([here](https://github.com/Joystream/youtube-synch/issues/149)) & conducted

## QA Environment

The fault tolerance QA testing was mainly done in the local environment by mocking different external APIs as unresponsive and checking the resilience of YT-synch Infrastructure in handling resulting exceptions.

## Execution

- Tested all RPC Node Failure scenarios  :white_check_mark:
- Tested all Query Node Failure scenarios  :white_check_mark:
- Tested all Google API Node Failure scenarios  :white_check_mark:
- Tested all Storage Node Failure scenarios  :white_check_mark:


## Fixes:
List of issues that were found after starting conducting QA (not all were necessarily part of QA plan, and were found while testing other use cases) and their fixes:

- https://github.com/Joystream/youtube-synch/pull/161
- https://github.com/Joystream/youtube-synch/pull/159
- https://github.com/Joystream/youtube-synch/pull/158
- [fix: ensure referrer channel is different from channel singing up for YPP](https://github.com/Joystream/youtube-synch/pull/164/commits/2038a194bc731adb93a6ee9b490cb1d06605d76c)
- [fix: dynamodb region missing error while running local instance](https://github.com/Joystream/youtube-synch/pull/164/commits/a20170aa0227afbba157dc3d55303755eaf872a0)
- [fix: skip syncing of a video if it gets deleted on YT after being tracked on YT-synch service](https://github.com/Joystream/youtube-synch/pull/164/commits/9cd03c6668fd10645ee37d2f431e481b55929588)
- https://github.com/Joystream/youtube-synch/issues/165

**Comment by bedeho** [comment]
Excellent work @zeeshanakram3
