### ISSUE TITLE
MVP rewards operator skripts

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#133]
@dmtrjsg commented on [Wed Jan 25 2023](https://github.com/Joystream/atlas/issues/3670)

## Context

In case 
#128 takes quite some time to build this issue encapsulates bear minimum of what needs to be done to operate the programme. 

## Scope

Count uploaded videos:
Create a script that counts the videos uploaded from date x till date y for a channel ID + returns meta data for videos (link to Gleev channel, title, category id)

New channels:
New channels created  from date x till date y + link to joystream and youtuben channel + Referrer ids.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203869223896657) by [Unito](https://www.unito.io)

**Comment by zeeshanakram3** [comment]
Addressed in #173
