### ISSUE TITLE
Remove `user.profile` scope

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/youtube-synch#144]
Right now during requesting user authorization for YPP backend, we specify three scopes `youtube.readonly`, `user.email` & `user.profile`

However, it seems that `user.profile` (provides user ID info) is not 100 required, so if YT-sync BE can keep on working properly without this scope, then we can safely remove this scope from the authorization request

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203936973646069) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Not possible easily  and can introduce bugs, so concluded not worth the effort. Closing
