### ISSUE TITLE
Deleted YT channel remains with record as Unverified, but from FE this channel looks like opted out

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#157]
## Test data
Deleted channel: https://www.youtube.com/channel/UClbnfYzpDVLRF9IrVs2JiAA // 
in Dynamo it has gleevypp06@gmail.com email
Joystream Channel ID = 6.

## Outcome
Expected result: channel turns to Opted Out.
Actual result: channel has record as Unverified in Dynamo, but on Atlas app seems to be opted out: 

YPP Dashboard does not show up:
<img width="1407" alt="Screenshot 2023-03-07 at 17 54 40" src="https://user-images.githubusercontent.com/93924525/223459885-e83fc265-dbcf-4726-b8a6-e9057c52ad19.png">

Tested for this channel:
<img width="793" alt="Screenshot 2023-03-07 at 17 54 53" src="https://user-images.githubusercontent.com/93924525/223459850-6820466f-cb6c-4263-b578-0124d60915cd.png">

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1204129112174494) by [Unito](https://www.unito.io)

**Comment by zeeshanakram3** [comment]
@dmtrjsg fixed in #159. Please retest whenever you have time. Thanks
