### ISSUE TITLE
Implement YT-synch service health/status monitoring for robust errors detection

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/youtube-synch#169]
For errors/exceptions which are not triggered by users (and thus are not returned in API response), they need to be pushed out to infra maintainers for robust detection & fix. We can look into integrating Checkly with YT-synch service

**Comment by bedeho** [comment]
I'm not sure if this issue and https://github.com/Joystream/youtube-synch/issues/170  are really entirely separate, so perhaps the following applies to both:

It would be great if the way such information is made available is sufficiently general that people can plug it into stuff  like https://www.atlassian.com/software/statuspage , which is a sort of industry standard for giving public visibility into how well some public service is working. With a general way of reporting such errors and metrics, we can avoid the need to actually build our own visualization and dashboards, and just use something like `Statuspage`.
