### ISSUE TITLE
Bug: while polling the Youtube, only first page of the videos for each channel is being fetched

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/youtube-synch#176]
### Problem

While doing Youtube polling and fetching the videos for a channel, YT returns a paginated response (with each page containing 50 videos), seems like only one page is being fetched & tracked in a DB. Hence, due to this bug currently only maximum of 50 videos are being synced for each channel.

**Comment by bedeho** [comment]
Will this automatically lead to full synch of existin channels when this problem is fixed, or does something manually need to be done?

**Comment by zeeshanakram3** [comment]
> Will this automatically lead to full synch of existin channels when this problem is fixed, or does something manually need to be done?

Yes, the syncing of remaining videos (which are not being tracked right now) will be automatic.

**Comment by zeeshanakram3** [comment]
- This issue was fixed in #177 & and has been already deployed.
- After the fix `~400` new videos across 6 participant channels were tracked and successfully published on Joystream.

cc. @bedeho @dmtrjsg

**Comment by bedeho** [comment]
Nice job sir!
