### ISSUE TITLE
Failed to upload large asset files to storage-node

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/youtube-synch#191]
# Context

The YT-synch instance is repeatedly failing to upload the media asset of a large youtube [video](https://www.youtube.com/watch?v=CF0Gddy8wDc)(~18 GB at 1080p) to the storage node. Each time storage-node/s is responding to the upload request with one of the following errors:

- `500 Internal Server Error`
- `413 Content Too Large`
- `502 Bad Gateway`

Investigate whether this is happening due to buggy implementation of upload logic in `youtube-synch` service. Or some limitation/bug in storage-node to handle large files.

**Comment by bedeho** [comment]
Oh, very interesting. Are you able to contact owner of node?

**Comment by zeeshanakram3** [comment]
> Oh, very interesting. Are you able to contact owner of node?

No, I didn't contact anyone. As the upload request failed on almost every storage node. So I will investigate on `youtube-synch` side first to see if there is some problem there.

**Comment by zeeshanakram3** [comment]
This issue was due to a reverse proxy (Caddy) configuration option. And has been addressed
