### ISSUE TITLE
Incorrect Youtube Quota usage calculation

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/youtube-synch#195]
# Context

Youtube tracks the API usage in the form of quota points (default max limit is 10,000 per day). Youtube Data API does not provide info about current quota usage So YouTube-synch BE manually tracks quota usage by aggregating the Quota used by each request based on this quota [calculation scheme](https://developers.google.com/youtube/v3/determine_quota_cost)

# Problem

There is some discrepancy b/w quota usage calculated by YT-synch & what is being shown Google console dashboard. **YT-synch calculates less than what is actually used.**

<img width="507" alt="image" src="https://github.com/Joystream/youtube-synch/assets/37098720/b754d20b-bca5-468b-bf59-4b1d4cbbc236">
<img width="502" alt="image" src="https://github.com/Joystream/youtube-synch/assets/37098720/b5ec3e73-54ea-40ef-b6d8-2f5e4eab341e">

YT-synch exposes the current quota usage/availability in API endpoint, and Atlas uses that to ensure whether creator can be onboarded successfully or not(if quota is not available Atlas asks creator to retry later).  **_Now if all quota has been consumed and YT-synch api says that quota is available(because it under calculated), this could create problem/confusion for creator onboarding_**

**Comment by bedeho** [comment]
oh, what do we do about this?

**Comment by zeeshanakram3** [comment]
> oh, what do we do about this?

There is a quota usage table provided by Youtube which lists what each API operation costs, hopefully, as a first step, by verifying the youtube-synch calculation against the cost of each operation specified in this table we should be able to identify the discrepancy.
<img width="810" alt="image" src="https://github.com/Joystream/youtube-synch/assets/37098720/b1b0a704-27a2-469c-bef3-d5acd0cf4dc7">

**Comment by zeeshanakram3** [comment]
Addressed in #201
