### ISSUE TITLE
Captcha for new membership creation

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#203]
@dmtrjsg commented on [Mon Jun 19 2023](https://github.com/Joystream/atlas/issues/4333)

For default membership creation captcha needs to be in place.  @KubaMikolajczyk pls add this to the designs
For YPP flow captcha is not required.

**Comment by attemka** [comment]
@zeeshanakram3 for the context:

we don't want users to fill in the captcha as they doing the signup via YPP flow. Current endpoint for handle creation expects captcha to be present. We can't make captcha optional as it will make the signup process vulnerable for the bots. One of the solutions will be to create a separate endpoint without the captcha and with the whitelist of YPP BE. Is it possible for YPP backend to send the user data to faucet endpoint if channel has passed all the requirements?

**Comment by dmtrjsg** [comment]
Discussed and arriving to suggestion (in order to skip captcha for YPP flow) of:
- YPP backend calling the extrinsic itself to impose the invitation lock for certain membership.

@bedeho can you approve or object to this?
