### ISSUE TITLE
Upgrade scripts for YPP ops - update entries that did not get paid last round

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#212]
## Context

For records that did not qualify for payments at all, with executing the `payRewards` command, it would be ideal to update Hubspot entries as well so its easier to do reporting.

## Scope

1. Update field `Latest Overall YPP Reward` to 0
2. Update field `Latest YPP reward status` to paid

The above need to be reset when we are calculating rewards
1. Overwrite `Latest Overall YPP Reward`  if status = paid 
2. add to previous value if status = to pay

**Comment by dmtrjsg** [comment]
Also these two small points are remaining:
Need to manually copy paste the first payout to the totals 
Need to manually update the "To Pay status" for the ones whose latest payout is 0

Would be nice to automate this as well 

cc @zeeshanakram3

**Comment by bedeho** [comment]
Perhaps I misunderstanding sometihng, but we def should not couple payout script with hubspot. payout script is a tool useful to any yt-synch user, hubspot is an artefact of how we are doing CRM for our marketing?

**Comment by dmtrjsg** [comment]
To be tested: after this new payout check if Friday evening channels are paid.
