### ISSUE TITLE
Sync only verified channels

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#224]
We need to only sync verified channels

**Comment by Taron0777** [comment]
hello my syncronization don`t working i don`t see my sync video .
my last video syncronization 6 days ago after this I am 22 videos I posted on my YouTube channel but they did not sync where is it? why is don`t working?

**Comment by bedeho** [comment]
There has been such huge demand in synching, so we had to pause to allow storage infrastructure in DAO to catch up, apologies for the inconvenience.

@dmtrjsg should we have some sort of global "synch indicator" in the YPP screen for creators, so they can understand that all synching is possibly not online at the moment?

**Comment by zeeshanakram3** [comment]
Addressed in #227
