### ISSUE TITLE
Add ability to update YPP syncing Category

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#255]
Context
Category can be updated by both Operator and Channel 

Scope:
- [ ] Add endpoint to updated category in the Dynamo DB by operator

**Comment by dmtrjsg** [comment]
@zeeshanakram3 can you pls add a short example of the request and endpoint url pls.

**Comment by zeeshanakram3** [comment]
> @zeeshanakram3 can you pls add a short example of the request and endpoint url pls.

## Documentation (Dev env)
Endpoint for changing category for the operator: https://52.204.147.11.nip.io/docs/#/channels/ChannelsController_setChannelCategoryByOperator
Endpoint for changing category by channel owner: https://52.204.147.11.nip.io/docs/#/channels/ChannelsController_updateCategoryChannel
