### ISSUE TITLE
Latest Reward Total in JOY and Total Paid are empty in Hubspot

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#289]
Checked a bunch of channels that signed up last week and were supposed to get paid.. I think we didn't pay them in the end.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1Z2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb4fc5a2e831725a2f691a82a461f684d53826c1/Screenshot%202023-10-25%20at%2019.30.26.png)

**Comment by dmtrjsg** [comment]
Attaching the full list of channels suspectedly not paid
[hubspot-crm-exports-ypp-customers-2023-10-25-2.csv](https://github.com/Joystream/youtube-synch/files/13167878/hubspot-crm-exports-ypp-customers-2023-10-25-2.csv)

**Comment by bedeho** [comment]
Why were they not paid?

**Comment by dmtrjsg** [comment]
Seems like it may have been the delay in Hubspot data update by YT BE.. checking all these channels now and they seem to have been paid. 

Closing the issue as resolved.
