### ISSUE TITLE
Validation on Verification

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#29]
## Context

Miro LInk > [LINK](https://miro.com/app/board/uXjVOn84FzE=/?moveToWidget=3458764529467745363&cot=14)

Action: Creator proves to our infrastructure that you own a youtube channel, using Google authentication service.
Terms:
Joystream channel avatar, cover, title and description is properly set.
YT channel is at least 3 months old.
YT channel has at least 10 videos, all published at least 1 month ago
YT channel has at least 50 followers
Amount: Three tiers of $JOY amount based on range of followers.

## Scope
- [ ] conduct validation of the assessment criteria
- [ ] based on the validation criteria described above assigns status: Authorised
- [ ] for authorised channels add a Tier: from 1 to 3

That's what we save to airtable

Referrer Joystream Channel ID (can be empty)
Joystream Channel ID
Youtube Channel Id

Tiers:
50 - 10k => 1
10k - 100k = > 2
100k + => 3

**Comment by dmtrjsg** [comment]
@bedeho what's the threshold for Creator Tiers in context of rewarding ❓ 

How about below: 

50 - 10k => 1
10k - 100k = > 2
100k + => 3

**Comment by dmtrjsg** [comment]
> what could be the difference in remuneration based on tiers?

This was an attempt to suggest a way to derive different payment scales for different Tiers.  For it to be effective I think the figures are somewhere between the opportunity cost of their time (performing actions)  and the cost of acquisition of incremental Atlas active user (calculated from Marketing funnel).

This also requires a conversation, so perhaps a talking point for the after standup.

**Comment by zeeshanakram3** [comment]
Implemented in https://github.com/Joystream/youtube-synch/pull/40
