### ISSUE TITLE
Channels missed sign up Rewards

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#291]
31 channels were not assigned sign up rewards by Calc script

```
31123
31117
31119
31106
31110
31107
31113
31111
31109
31108
31121
31116
31112
28946
31114
31115
30797
30352
30729
30599
30474
28808
28657
28167
29793
28422
28374
31022
30005
27840
26818
```

**Comment by bedeho** [comment]
why?

**Comment by dmtrjsg** [comment]
Based on my investigation it seems that such channels were marked as "checked" at the time when their status was `unverified`. So when next week's calc script ran it skipped such channels as "checked already".

The solution would be to skip "unverified" channels with calculation script or sync only verified channels to HS.

**Comment by dmtrjsg** [comment]
paid
