### ISSUE TITLE
Channel not paid but marked as paid on Hubspot

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#308]
gleev Channel ID: 34269
Channel Reward acc: j4To6jgKfy8MgiMRDXzc15ggN8AnFBp6jPehrTtjBPLySSoXE

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd01HQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c8bc36f4cbf00253a36ff28c7a9e444fe835161/Screenshot%202023-11-24%20at%2015.36.47.png)

<img width="892" alt="Screenshot 2023-11-24 at 15 35 37" src="https://github.com/Joystream/youtube-synch/assets/93924525/cdf794b4-35be-45ad-a08e-892124e09cc0">

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0lHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa85f751694fdcb92a3e02c3fec00a0d47714a44/Screenshot%202023-11-24%20at%2015.37.20.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0VHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ec7374d3ac6c2944f51764bb721965221ee2b3a/Screenshot%202023-11-24%20at%2015.37.31.png)

**Comment by bedeho** [comment]
Can you please elaborate on what happened here. Why happened that was unexpected, and how was it detected?

**Comment by zeeshanakram3** [comment]
Addressed in https://github.com/zeeshanakram3/youtube-synch/commit/2b3ecfbe761408502deaaaf137efba855241a679
