### ISSUE TITLE
Update syncing rules for historical videos of YPP channels

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#324]
## Context
Objective is to cut infra costs for storage of synced videos from YT

## Scope

**Target state**

After sign up each channel has an allowance of 5 latest videos synced before the verification by the YPP team is done and the YPP tier is assigned. After verification additional videos will be synced:

- Max of 5 videos OR 1 GB for channel with **bronze** tier (no additional syncing)  🥉
- Max of 100 videos OR 10 GB for channel with **silver** tier 🥈
- Max of 250 videos OR 100 GB for channel with **gold** tier 🥇
- Max of 1000 videos OR 1 TB  for channel with with **diamond** **tier** 💎

⚠️ For any channel max size of a single synced video is 15 GB
⚠️ For any channel max duration of synced video is 3 hrs

**Comment by zeeshanakram3** [comment]
> Max of 5 videos OR 1 GB for channel with bronze tier (no additional syncing) 🥉
Max of 100 videos OR 10 GB for channel with silver tier 🥈
Max of 250 videos OR 100 GB for channel with gold tier 🥇
Max of 1000 videos OR 1 TB for channel with with diamond tier 💎

Question: this applies to historical videos only or all videos?

**Comment by zeeshanakram3** [comment]
Ah, my bad, it's in the issue title ;)

**Comment by zeeshanakram3** [comment]
Addressed in #325
