### ISSUE TITLE
Extra sync reward for linking back to Gleev

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#326]
## Context
For creator rewards calculation, all videos that are tagged with #watchOnGleev hashtag will need to get 10% extra rewards for syncing. 

## Scope
- [ ] Add column on hubspot where linkback bonus is calculated separate to synced rewards and populate with script calc script

**Comment by bedeho** [comment]
tagged where? in the description?

but what is the value to just have the tag? I dont think I have ever seen or paid attention to any tag on ny youtube description
