### ISSUE TITLE
Update Reward Script with new rewards

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#327]
## Context
https://github.com/Joystream/atlas/issues/6194

## Scope

New values:

-YPP Dashboard

YPP sign up |   | USD
  | Bronze | 1
  | Silver | 25
  | Gold | 50
  | Diamond | 100
 
 
YPP sync |   |  
  | Bronze | 0
  | Silver | 1
  | Gold | 2
  | Diamond | 5
 
Referrals (for rewards calc)
  | Bronze | 0.5
  | Silver | 12.5
  | Gold | 25
  | Diamond | 50

**Comment by zeeshanakram3** [comment]
Addressed in https://github.com/zeeshanakram3/youtube-synch/commit/32b5a164210f3f48871d5be79e89e2a9b3d3277a
