### ISSUE TITLE
Synch Meeting Agenda

### ISSUE THREAD

**Issue by bedeho** [Joystream/youtube-synch#42]
- multiple resolutions: if we can at least get playback to work, then infra can plug in... conditional on not becoming redundant or in conflict with fuutre adaptive streaming.

- how are we dealing with category mapping? I believe it should be static, and creator should provide input in signup flow, but I don't know where we stand. This would also be a good place for a creator to discover that they may be trying to get into a service which does not match their content, it's not so clear how Gleev for example will signal this otherwise, perhaps a separate screen is needed about this regardless?

- Continuation of prior point. Does Gleev need some more custom messaging to make sure its clear what its about? e.g. Updating YPP page? 

- Continuation of prior point. Should this be configurable so that Vintio and others can change?

- What is status of YPP being configruable as on or off in Atlas instance?

- How will we policy wise deal with people signing up, say with a cooking channel, even if we add all the messaging described? Obviously tehy should not receie a payout, but how will they learn about why they are not a fit?

- It's very unclear for me how YPP should work outside of Gleev+Vinteo: YPP has distinct parts
  1. who pays (until council does) and what are terms?: operationally it seems complex for us to start paying for all sorts of other gateways, so probably not?
  2. what creator backend to use: if there are distinct backends, different gateways may end up onboarding same creator, but perhaps this is totally fine, as council in the end probably will not reward duplicates?
  3. what synching infra to use: these could all be totally distinct.

**Comment by dmtrjsg** [comment]
Youtube [categories list>](https://influenceonyoutube.com/create-videos-for-youtube-start-now/how-to-choose-a-category-on-youtube/)

**Comment by dmtrjsg** [comment]
### Resolutions after the meeting 

1️⃣  At launch YT synch service would pull in 1080 default. If not available, then 720.

**Multiple resolutions** 

Will be added later, perhaps right after launch. 

Implementation will not be too hard as you can just fetch multiple and add them to channel bag with diff meta. Doable at reasonable cost. Some metadata complications for QN, and design work will be reqd for Atlas team.

**Does it conflict with Adaptive streaming?**
There’s no reason to assume there is a conflict, it requires quite some extra work.
Will be added to post-mainnet scope separately

2️⃣ CATEGORIES
1. YT sync scraps the YT category, and lets creator select a single category. Inform users that this will be propagated to all videos, but can be changed manually.
2. What they select is default display category for the video category.

3️⃣ . Custom messaging for Gleev on Sign up flows for creators and viewers landing page. 
Dima and Adam will figure out all the entry points and messaging that needs to be designed to inform users on what value prop does it have. 

4️⃣ YPP flow AND Gleev content vertical messaging needs to be optional to set up/configurable. 

5️⃣ We are hiding the YPP, but not splitting the code base.

6️⃣  We will re-enforce the message that content category is important to adhere to in YPP landing page, Onboarding flow and YPP Dashboard. This messaging will need to be re-factored so its customisable.

7️⃣ YPP Ops

1. Gateway operators pay for their YPP Programme
- https://github.com/Joystream/joystream/issues/4337
2. Distinct Backends and separate Auth flow 
3. Separate Sync Infra
