### ISSUE TITLE
Syncing YT channel without doing authentication

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/youtube-synch#54]
Sync real Youtube channels without doing their authentication in the YPP backend to test the complete syncing setup. Compile the list of YT channels and their videos (i.e., in JSON format). Write a script to update the `channels` and `videos` Dynamodb tables with the compiled list, and then start syncing the videos.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203771960273356) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Will it be possible to also just add new channels and videos to the service while it is live? because if there will be some API or CLI which allows this, then the process of automated adding of large numbers of channels+videos can just be some utility script that uses this interface.

**Comment by zeeshanakram3** [comment]
Sure. I will add an authenticated API endpoint for infrastructure operators, which scripts can use to update channels and videos periodically.

**Comment by dmtrjsg** [comment]
@zeeshanakram3 pls link the PR and close the issue.
