### ISSUE TITLE
Remove Tier calculation from BE service and only keep number of subscribers

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#66]
@dmtrjsg commented on [Wed Nov 23 2022](https://github.com/Joystream/marketing/issues/299)

## Context

Decision was made to move the Tiers configuration to the App side, so needs to be remove from BE.

## Scope
- [ ] Remove Tiers calculation from BE and only keep subscribers.
- [ ] Update all related API endpoints

**Comment by zeeshanakram3** [comment]
Addressed in #63
