### ISSUE TITLE
Create Endpoint to Expose YPP Requirements

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#68]
## Scope
- [ ] Create endpoint to expose minimum requirements to Atlas

## Context

As part of the YPP flow the minimum requirements are imposed on qualifying channels with params:

Age (date created)
Number of videos
Number of subscribers

Currently these are hardcoded on the BE side and FE modal:
![Screenshot 2022-11-30 at 17.59.34.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/8d7dc8f9-b89c-490e-96b8-cd1af31a29f9)

We want to make it parametrised to be easily tweaked by JSG team and External GW operators

**Comment by zeeshanakram3** [comment]
Addressed in #73
