### ISSUE TITLE
Propagate language to synced YT videos from Channel Default Language

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#76]
@dmtrjsg commented on [Thu Dec 08 2022](https://github.com/Joystream/marketing/issues/319)

- [ ] When videos are pulled via auto-sync, take the language from the Joystream Channel.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1204184832168132) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@zeeshanakram3 pls add the PR here and close the issue if done.

**Comment by zeeshanakram3** [comment]
readdressed in 641f243
