### ISSUE TITLE
Issues with synced videos

### ISSUE THREAD

**Issue by drillprop** [Joystream/youtube-synch#81]
- [ ] it seems not all of the synced videos have audio
- [ ] they don't have a duration set. In QN It's set to just `null`. 
- [x] I don't know if it's actually fixable, but thumbnails have a weird format with black bars on the top and bottom: 
![image](https://user-images.githubusercontent.com/51168865/206457388-e14cce45-db99-4bfe-9473-d2b52689734b.png)
They are more square-like. This is how it looks in atlas: 
![image](https://user-images.githubusercontent.com/51168865/206457680-9dca9a6f-2a4c-4827-9b92-ad12934b0dea.png)
- [ ] they don't have mediaMetadata set correctly.  `pixelHeight`, `pixelWidth`, is not set. Also `mimeMediaType` in `encoding` is null. Although, I'm not sure if we actually need all these values, and if we can live without these properties.

Questions: 
- Should we fill the `publishedBeforeJoystream` field in this case? They were created on youtube first, so I guess we could add the proper date to QN as well
- There are a couple of properties that are just null, and I'm wondering if we should keep them like that in the atlas. Those are license, language, isExplicit, hasMarketing.

**Comment by dmtrjsg** [comment]
Resolution: 
`publishedBeforeJoystream` (date field) will be left empty. One possible use case is to use it in the recommendation and search relevancy rules so having some sort of indication of original date is helpful ONLY if we are pulling in historical videos.
