### ISSUE TITLE
Post request to `/users` is not returning email anymore

### ISSUE THREAD

**Issue by drillprop** [Joystream/youtube-synch#84]
it looks like `tokenInfo` doesn't have a field email.
![image](https://user-images.githubusercontent.com/51168865/206738528-9755b6ec-41fa-475a-9a31-7858bf5a2edc.png)
![image](https://user-images.githubusercontent.com/51168865/206738551-66bdfbbf-b93d-4f3a-90e2-317e6b8b097e.png)
We used email to populate the details form in ypp flow: 
![image](https://user-images.githubusercontent.com/51168865/206738893-fa3aa8e4-f90b-4c8b-b7ea-145623354082.png)

Could be caused by changes to the `GOOGLE_AUTH_PARAMS` in atlas(changing `scope`, or `acces_type`)

**Comment by dmtrjsg** [comment]
Needs to be fixed on the Atlas side. We just need to add the scope with fetching email connected to YT channel.

**Comment by dmtrjsg** [comment]
Issue moved to [Joystream/atlas #3566](https://github.com/Joystream/atlas/issues/3566) via [**Zenhub**](https://www.zenhub.com/)
