### ISSUE TITLE
Issue with syncing premiere YouTube video

### ISSUE THREAD

**Issue by drillprop** [Joystream/youtube-synch#85]
As the title says
![image](https://user-images.githubusercontent.com/51168865/207035651-81221f75-45d8-4e7a-9749-1591cfa4f56f.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203869229009403) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@drillprop pls add small description on how to reproduce

**Comment by dmtrjsg** [comment]
Nice work 👍  ✅
