### ISSUE TITLE
Fetch 1080 videos

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#89]
@dmtrjsg commented on [Wed Dec 14 2022](https://github.com/Joystream/marketing/issues/322)

## Context
In some cases multiple resolutions videos are synced without audio. 

## Scope
- [ ] If video has multiple streams we can stick with 1080 (if not available 720), and make sure we pull in the audio-track.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1204136400231976) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
⚠️ if 1080 only resolution it will be synced with no audio.

**Comment by zeeshanakram3** [comment]
addressed in #160
