### ISSUE TITLE
Youtube Quota rationing b/w creator signups and syncing service.

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/youtube-synch#98]
## Problem

If syncing service has consumed all of Youtube's Daily Quota (**10,000** API calls), then creators won't be able to sign up for the  YPP program until the next day when Quota gets reset; which I think is a more critical action than syncing content.

## Solution

Implement Quota rationing for both signup activities & syncing content, respectively. E.g., say `5%` or `10%` quota is reserved for creators' onboarding which syncing service can't use.

**Comment by dmtrjsg** [comment]
5% seems reasonable 👍  If the quota is fully exhausted, seems like we need a specific error to be shown on the App side. "Due to high demand, we've reached the quota on the daily new sign ups. Please try again tomorrow." in the toaster notification when auth is attempted.

**Comment by drillprop** [comment]
> 5% seems reasonable 👍 If the quota is fully exhausted (even this 5%), seems like we need a specific error to be shown on the App side. "Due to high demand, we've reached the quota on the daily new sign ups. Please try again tomorrow." in the toaster notification when auth is attempted @drillprop wdyt.

So this will happen after a user tried to sign up? If yes, we could use this for now. Ideally, it would be great to show the message on the YPP landing page before the user starts the whole process

**Comment by dmtrjsg** [comment]
@drillprop yes totally, drafting two separate cases in the related Atlas issue :)

**Comment by dmtrjsg** [comment]
Set to 5% in the current implementation.
