### ISSUE TITLE
License for Auto-sync

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/youtube-synch#99]
@dmtrjsg commented on [Wed Dec 14 2022](https://github.com/Joystream/marketing/issues/321)

## Context

YT videos have 2 licenses: Youtube License and Creative Commons. 

The license will be finalised in this issue:
- https://github.com/Joystream/atlas/issues/3442

## Scope
- [ ]  Add  "Joystream Standard License" to the licenses JSON

Set name to Joystream Standard
Long name to Joystream Standard license
Atrribution = false
Description "Joystream Standard License description pending".
URL = "" (nothing)

- [ ] Map  YT standard licenses to Joystream Standard License during auto-sync. 
- [ ] map Creative Commons to CC0 license during auto-sync.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203869227164646) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
LIst of existing licenses: 
https://github.com/Joystream/atlas/blob/master/packages/atlas/src/data/knownLicenses.json

Also exists in metaprotocol protobuff package

**Comment by dmtrjsg** [comment]
@zeeshanakram3 what will be the code for the license? If not done let's make it 1009.

**Comment by zeeshanakram3** [comment]
> @zeeshanakram3 what will be the code for the license? If not done let's make it 1009.

I set it to 1000 based on the custom license code from the `knownLicense.json` file. But, sure, I will change it. Thanks for letting me know.

**Comment by dmtrjsg** [comment]
The license code will be 1009.

**Comment by dmtrjsg** [comment]
@zeeshanakram3 just a quick update: 

`CCO license not showing as well for synced videos`

YT video link: https://www.youtube.com/watch?v=KIrCt7D-vCo
JS video link: https://atlas-git-ypp-joystream.vercel.app/video/429

<img width="771" alt="Screenshot 2023-02-01 at 16 47 27" src="https://user-images.githubusercontent.com/93924525/216107750-d59f5ec0-9875-41eb-8494-b6e003f04b48.png">

**Comment by dmtrjsg** [comment]
ER:
Standard YT license -> Joystream license
CCO license -> CCO on joystream

AR:
🔴 Tested for CCO license and it was synced with Joystream License

Video tested with: 
https://www.youtube.com/watch?v=JSivIdU2B7I
https://atlas-git-dev-joystream.vercel.app/video/134

Screenshots: 

<img width="857" alt="Screenshot 2023-02-10 at 17 26 31" src="https://user-images.githubusercontent.com/93924525/218103577-f296f465-81a3-4cb6-93a8-a3a63972820e.png">
<img width="883" alt="Screenshot 2023-02-10 at 17 26 12" src="https://user-images.githubusercontent.com/93924525/218103583-cb4acaa3-8be0-4fd9-9b7c-59b914060d7d.png">
